# Generated by Django 5.2.13 on 2026-05-16 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_updated_at_goalupdate_managercheckin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalupdate',
            old_name='progress_score',
            new_name='achievement_value',
        ),
        migrations.RemoveField(
            model_name='goalupdate',
            name='actual_achievement',
        ),
        migrations.RemoveField(
            model_name='goalupdate',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='goalupdate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='managercheckin',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='managercheckin',
            name='goal_update',
        ),
        migrations.AddField(
            model_name='goalupdate',
            name='employee_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='managercheckin',
            name='discussion_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='managercheckin',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goal'),
        ),
        migrations.AddField(
            model_name='managercheckin',
            name='manager_feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='goalupdate',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goal'),
        ),
        migrations.AlterField(
            model_name='goalupdate',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='goalupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='managercheckin',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
